---
default_stages: [commit, push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: '2.18.1'
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^js/plugins/.*$|^bootstrap-4\.1\.1-dist/.*$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        exclude: package\.json$|package-lock\.json$
      - id: trailing-whitespace
        exclude: ^js/plugins/.*$|^bootstrap-4\.1\.1-dist/.*$
  # - repo: git://github.com/Lucas-C/pre-commit-hooks
  #  rev: v1.1.9
  #  hooks:
  #    - id: forbid-tabs
  #    - id: remove-tabs
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        name: Run codespell
        description: Check spelling with codespell
        entry: codespell --ignore-words=codespell.txt
        exclude: ^package-lock\.json$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        name: Run markdownlint
        entry: markdownlint -c .github/linters/.markdown-lint.yml
        exclude: ^js/plugins/.*$|^bootstrap-4\.1\.1-dist/.*$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint --strict -c .github/linters/.yaml-lint.yml .
        types: [yaml]
