import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="header__wrapper">
          <div className="header__container">
            <div className="header_logo_container">
              <a href="#" className="header__logo">
                One
              </a>
            </div>
            <div className="header_links_container">
              <a href="#product" className="header__link">
                Product
              </a>
              <a href="#product" className="header__link">
                Customers
              </a>
              <a href="#product" className="header__link">
                Pricing
              </a>
              <a href="#product" className="header__link">
                Manifesto
              </a>
              <a href="#product" className="header__link">
                Blog
              </a>
              <a href="#product" className="header__link gray">
                Log in
              </a>
              <a href="#product" className="header__link black">
                Try it now
              </a>
            </div>
          </div>
        </div>
      </header>
      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
